#tomcat配置
server:
  max-http-header-size: 8192
  #tomcat端口
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    #tomcat配置参数编码
    uri-encoding: UTF-8

spring:
# 数据库的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 使用sqlServer数据库
    url: jdbc:sqlserver://39.98.253.222:1433;SelectMethod=cursor;DatabaseName=wxmp
    username: sa
    password: bd123456
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    prefix: classpath:/templates/
    # 是否启用缓存
    cache: false

  #热部署
  devtools:
    restart:
      #热部署生效 true|false
      enabled: true
      #设置重启的目录，检索目录(resources/static、resources/templates)
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

  #redis单机配置,本处只使用单机redis版本
  redis:
    host: 127.0.0.1
    port: 6379
    #默认db=0
    database: 0
    # 密码（默认为空）
    password:
    # 连接超时时长（毫秒）
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


#是否开启swagger接口页面，true|false
swagger:
  open: true

#是否开启通用日志打印
auto:
  log:
    # 是否输出请求信息
    enabled: true

# 日志配置
logging:
  level:
    com.afeng: debug
    org.springframework: warn

#mybatis配置
mybatis:
  #mybatis扫描mapper映射SQL-XML目录路径范围，需要类上有@Mapper注解
  mapper-locations: classpath*:admin/*.xml
  #mybatis扫描model实体类目录路径范围，需要model类上有@Alias注解
  type-aliases-package: com.afeng.**.model
  configuration:
    #是否开启驼峰命名，如果开启后将会自动把数据库如字段user_name映射到实体类字段userName中， true|false
    map-underscore-to-camel-case: true
    #默认分批条数，例如查询结果总条数为10000条，为了避免数据量过大导致OOM，将会分开10次查询后合并返回的结果
    default-fetch-size: 100
    #设置超时时间，它决定驱动等待数据库响应的秒数
    default-statement-timeout: 60

# PageHelper分页插件
pagehelper:
  # 选择数据库模式，不选择则自动识别 oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
#  helperDialect: sqlserver2012
  offsetAsPageNum: true
  pageSizeZero: true
  params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
  reasonable: true
  rowBoundsWithCount: true
  supportMethodsArguments: true

