#tomcat配置
server:
  max-http-header-size: 8192
  #tomcat端口
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    #tomcat配置参数编码
    uri-encoding: UTF-8

spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      #是否开启多文件上传
      enabled: true
      file-size-threshold: 0
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

  #邮件
  mail:
    default-encoding: UTF-8
    host: smtp.162.com
    password: xxxxxxxx
    username: 283215159@163.com
# 数据库的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 使用sqlServer数据库
    url: jdbc:sqlserver://127.0.0.1:1433;SelectMethod=cursor;DatabaseName=freedom
    username: sa
    password: 123456
    # druid连接池配置
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    prefix: classpath:/templates/
    # 是否启用缓存
    cache: false

  #热部署
  devtools:
    restart:
      #热部署生效 true|false
      enabled: true
      #设置重启的目录，检索目录(resources/static、resources/templates)
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

  #redis单机配置,本处只使用单机redis版本
  redis:
    host: 127.0.0.1
    port: 6379
    #默认db=0
    database: 0
    # 密码（默认为空）
    password:
    # 连接超时时长（毫秒）
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


#是否开启通用日志打印
auto:
  log:
    # 是否输出请求信息
    enabled: true

# 日志配置
logging:
  level:
    com.afeng: debug
    org.springframework: warn

#mybatis配置
mybatis:
  #mybatis扫描mapper映射SQL-XML目录路径范围，需要类上有@Mapper注解
  mapper-locations: classpath*:mapper/**/*.xml
  #mybatis扫描model实体类目录路径范围，需要model类上有@Alias注解
  type-aliases-package: com.afeng.**.model
  configuration:
    #是否开启驼峰命名，如果开启后将会自动把数据库如字段user_name映射到实体类字段userName中， true|false
    map-underscore-to-camel-case: true
    #默认分批条数，例如查询结果总条数为10000条，为了避免数据量过大导致OOM，将会分开10次查询后合并返回的结果
    default-fetch-size: 100
    #设置超时时间，它决定驱动等待数据库响应的秒数
    default-statement-timeout: 60

# PageHelper分页插件
pagehelper:
  # 选择数据库模式，不选择则自动识别 oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
#  helperDialect: sqlserver2012
  offsetAsPageNum: true
  pageSizeZero: true
  params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
  reasonable: true
  rowBoundsWithCount: true
  supportMethodsArguments: true

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /admin/login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString(deskey.getEncoded()));
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false


# 代码生成
gen:
  # 作者
  author: afeng
  # 默认生成包路径 admin 需改成自己的模块名称 如 system monitor app
  packageName: com.afeng.module.admin
  # 自动去除表前缀 true|false，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_,app_

# 自定义属性，可以在Controller中读取
afeng:
  hello: Hello GOD
  # 名称
  name: afeng
  # 版本
  version: 4.2.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关 true|false
  demoEnabled: true
  # 启用admin管理后台模块开关 true|false
  adminManageEnabled: true
  # 获取ip地址开关 true|false
  addressEnabled: false
  # 是否启用OSS，启用后上传文件将上传到云存储 true|false
  ossEnabled: true
  # 本地文件上传路径，当前项目运行目录下的upload 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: ${user.dir}/upload

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5



